#theme: jekyll-theme-time-machine [achi]
# # theme: jekyll-theme-slate [achi]
theme: jekyll-theme-minimal
#theme: jekyll-theme-midnight
#theme: jekyll-theme-hacker
#theme: jekyll-theme-dinky
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect

# Not considering
# theme: jekyll-theme-modernist
