#theme: jekyll-theme-time-machine
theme: jekyll-theme-tactile
#theme: jekyll-theme-slate
#theme: jekyll-theme-modernist
#theme: jekyll-theme-minimal
#theme: jekyll-theme-midnight
#theme: jekyll-theme-hacker
#theme: jekyll-theme-dinky
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect
