#theme: jekyll-theme-time-machine [achi]
# # theme: jekyll-theme-slate [achi]
# theme: jekyll-theme-minimal [achi]
# theme: jekyll-theme-midnight [achi]
theme: jekyll-theme-dinky
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect

# Not considering
# theme: jekyll-theme-hacker [aiwi for me but can be kewl as well]
# theme: jekyll-theme-modernist
